# Generated by Django 5.1.5 on 2025-02-26 06:37

import apps.common.models.fields
import apps.common.utils
import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('logo', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='loyiha logosi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
            ],
            options={
                'verbose_name': 'Loyiha ',
                'verbose_name_plural': '1. Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasmi')),
                ('icon', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='belgisi(.svg')),
                ('title', models.TextField(max_length=511, verbose_name='sarlavhasi')),
                ('title_uz', models.TextField(max_length=511, null=True, verbose_name='sarlavhasi')),
                ('title_ru', models.TextField(max_length=511, null=True, verbose_name='sarlavhasi')),
                ('title_en', models.TextField(max_length=511, null=True, verbose_name='sarlavhasi')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='batafsil')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project', verbose_name='loyiha')),
            ],
            options={
                'verbose_name': 'Kirish ',
                'verbose_name_plural': '2. Kirish',
            },
        ),
        migrations.CreateModel(
            name='GoalAndMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=511, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('icon', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='belgisi(.svg)')),
                ('text', models.TextField(verbose_name='batafsil')),
                ('text_uz', models.TextField(null=True, verbose_name='batafsil')),
                ('text_ru', models.TextField(null=True, verbose_name='batafsil')),
                ('text_en', models.TextField(null=True, verbose_name='batafsil')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Maqsad va vazifa ',
                'verbose_name_plural': '4. Maqsad va vazifalar ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('email', models.EmailField(max_length=255, verbose_name='email pochta')),
                ('message', models.TextField(verbose_name='xabar')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='loyiha')),
            ],
            options={
                'verbose_name': 'Fikr ',
                'verbose_name_plural': '8. Fikrlar',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=512, verbose_name='hujjat nomi')),
                ('title_uz', models.CharField(max_length=512, null=True, verbose_name='hujjat nomi')),
                ('title_ru', models.CharField(max_length=512, null=True, verbose_name='hujjat nomi')),
                ('title_en', models.CharField(max_length=512, null=True, verbose_name='hujjat nomi')),
                ('file', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='hujjat fayli')),
                ('type', models.CharField(max_length=6)),
                ('file_size', models.FloatField(default=0, verbose_name='hujjat hajmi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Hujjat ',
                'verbose_name_plural': '5. Hujjatlar',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='sarlavhasi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='sarlavhasi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='sarlavhasi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='sarlavhasi')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='batafsil')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasmi')),
                ('youtube_url', models.URLField(max_length=255, verbose_name='youtubedan havola')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendarplans', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha haqida ',
                'verbose_name_plural': '3. Loyiha haqida ',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('title', models.CharField(max_length=511, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=511, null=True, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='batafsil')),
                ('text_uz', models.TextField(null=True, verbose_name='batafsil')),
                ('text_ru', models.TextField(null=True, verbose_name='batafsil')),
                ('text_en', models.TextField(null=True, verbose_name='batafsil')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectdocuments', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Hujjat ',
                'verbose_name_plural': '6. Loyiha Hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Ism-familiyasi')),
                ('full_name_uz', models.CharField(max_length=100, null=True, verbose_name='Ism-familiyasi')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='Ism-familiyasi')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='Ism-familiyasi')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=100, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(max_length=100, null=True, verbose_name='Lavozimi')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-maili')),
                ('avatar', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='Rasmi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmembers', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': "Jamoa a'zolari ",
                'verbose_name_plural': "7. Jamoa a'zolari",
            },
        ),
    ]
