# Generated by Django 5.1.5 on 2025-02-25 14:20

import apps.common.models.fields
import apps.common.utils
import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='nomi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
            ],
            options={
                'verbose_name': 'Tadbir kategoriyasi ',
                'verbose_name_plural': '1.Tadbirlar kategoriyalari ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('name', models.CharField(max_length=256, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=256, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='nomi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
            ],
            options={
                'verbose_name': 'Yangiliklar kategoriyasi ',
                'verbose_name_plural': '3.Yangiliklar kategoriyalari ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('name', models.CharField(max_length=512, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=512, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=512, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=512, null=True, verbose_name='nomi')),
            ],
            options={
                'verbose_name': 'Yangiliklar tegi ',
                'verbose_name_plural': '4.Yangiliklar teglari',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=512, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=512, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=512, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=512, null=True, verbose_name='sarlavha')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='matn')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='matn')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='matn')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='matn')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='Rasm')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('views_count', models.PositiveBigIntegerField(default=0, verbose_name="ko'rganlar soni")),
                ('date', models.DateTimeField(verbose_name='tadbir kuni')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='davlat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.eventcategory', verbose_name='kategoriyasi')),
            ],
            options={
                'verbose_name': 'Tadbir ',
                'verbose_name_plural': '2.Tadbirlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasm')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.event', verbose_name='tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir galareyasi',
                'verbose_name_plural': 'Tadbirlar Galareyalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasm')),
                ('title', models.CharField(max_length=256, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='batafsil')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='batafsil')),
                ('views_count', models.PositiveBigIntegerField(default=0, verbose_name="ko'rganlar soni")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='davlat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.newscategory', verbose_name='kategoriyasi')),
                ('tags', models.ManyToManyField(to='news.newstag', verbose_name='teglar')),
            ],
            options={
                'verbose_name': 'Yangilik ',
                'verbose_name_plural': '5.Yangiliklar ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasm')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik galareyasi',
                'verbose_name_plural': 'Yangiliklar Galareyalari',
            },
        ),
    ]
