# Generated by Django 5.1.5 on 2025-02-14 12:13

import apps.common.models.fields
import apps.common.utils
import ckeditor_uploader.fields
import django.core.validators
import phonenumber_field.modelfields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('full_name', models.CharField(max_length=256, verbose_name='F.I.SH')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefon raqam')),
                ('question', models.TextField(verbose_name="Yo'llangan savoli")),
            ],
            options={
                'verbose_name': 'Kelib tushgan savol',
                'verbose_name_plural': '3. Kelip tushgan savollar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=256, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='sarlavha')),
                ('address', models.CharField(max_length=1024, verbose_name='Yuridik manzili')),
                ('address_uz', models.CharField(max_length=1024, null=True, verbose_name='Yuridik manzili')),
                ('address_ru', models.CharField(max_length=1024, null=True, verbose_name='Yuridik manzili')),
                ('address_en', models.CharField(max_length=1024, null=True, verbose_name='Yuridik manzili')),
                ('emails', models.EmailField(max_length=254, unique=True, verbose_name='elektron pochta')),
                ('phones', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='telefon raqamlar')),
                ('main_phone_number', apps.common.models.fields.PhoneField(max_length=15, validators=[django.core.validators.RegexValidator(message='15 ta raqamga ruhsat berilgan. Standart raqam talab qilinadi', regex='^\\+?1?\\d{9,15}$')], verbose_name="asosiy bog'lanish raqami")),
                ('location', models.URLField(verbose_name='xarita manzili')),
                ('latitude', models.CharField(blank=True, max_length=128, null=True, verbose_name='kengligi')),
                ('longitude', models.CharField(blank=True, max_length=128, null=True, verbose_name='uzunligi')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtube')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('whatsapp', apps.common.models.fields.PhoneField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='15 ta raqamga ruhsat berilgan. Standart raqam talab qilinadi', regex='^\\+?1?\\d{9,15}$')], verbose_name='whatsapp raqami')),
            ],
            options={
                'verbose_name': "Bog'lanish ",
                'verbose_name_plural': "4. Bog'lanish",
            },
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('full_name', models.CharField(max_length=256, verbose_name='F.I.SH')),
                ('full_name_uz', models.CharField(max_length=256, null=True, verbose_name='F.I.SH')),
                ('full_name_ru', models.CharField(max_length=256, null=True, verbose_name='F.I.SH')),
                ('full_name_en', models.CharField(max_length=256, null=True, verbose_name='F.I.SH')),
                ('position', models.CharField(max_length=256, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=256, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=256, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(max_length=256, null=True, verbose_name='Lavozimi')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasmi')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='elektron pochtasi')),
                ('reception_days', models.CharField(max_length=256, verbose_name='ish kunlari')),
                ('reception_days_uz', models.CharField(max_length=256, null=True, verbose_name='ish kunlari')),
                ('reception_days_ru', models.CharField(max_length=256, null=True, verbose_name='ish kunlari')),
                ('reception_days_en', models.CharField(max_length=256, null=True, verbose_name='ish kunlari')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('description_uz', models.TextField(null=True, verbose_name='tavsif')),
                ('description_ru', models.TextField(null=True, verbose_name='tavsif')),
                ('description_en', models.TextField(null=True, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': "Bog'lanishga javobgar odam ",
                'verbose_name_plural': "5. Bog'lanishga javobgar odam",
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=255, verbose_name='davlat nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='davlat nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='davlat nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='davlat nomi')),
                ('flag', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name="davlat bayrog'i")),
            ],
            options={
                'verbose_name': 'Davlat ',
                'verbose_name_plural': '7. Davlatlar ',
            },
        ),
        migrations.CreateModel(
            name='FAQTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='sarlavha')),
            ],
            options={
                'verbose_name': 'Savol va javob tegi',
                'verbose_name_plural': '1. Savol va javob teglari',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('full_name', models.CharField(max_length=256, verbose_name='F.I.SH')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('message', models.TextField(verbose_name="Yo'llangan xabar")),
            ],
            options={
                'verbose_name': 'Kelib tushgan xabar',
                'verbose_name_plural': '6. Kelib tushgan xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('slug_from_lang', models.CharField(blank=True, choices=[('uz', "o'zbekcha"), ('ru', 'ruscha'), ('en', 'inglizcha')], max_length=64, null=True, verbose_name='slugning tilini tanlash')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=256, verbose_name='sarlavhasi')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='sarlavhasi')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='sarlavhasi')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='sarlavhasi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='mazmuni')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmuni')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmuni')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmuni')),
            ],
            options={
                'verbose_name': 'Statik sahifa ',
                'verbose_name_plural': '8. Statik sahifalar',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('question', models.TextField(verbose_name='Savol')),
                ('question_uz', models.TextField(null=True, verbose_name='Savol')),
                ('question_ru', models.TextField(null=True, verbose_name='Savol')),
                ('question_en', models.TextField(null=True, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('answer_uz', models.TextField(null=True, verbose_name='Javob')),
                ('answer_ru', models.TextField(null=True, verbose_name='Javob')),
                ('answer_en', models.TextField(null=True, verbose_name='Javob')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('tags', models.ManyToManyField(to='common.faqtag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'savol va javob',
                'verbose_name_plural': '2. Savollar va javoblar',
                'ordering': ('order',),
            },
        ),
    ]
