# Generated by Django 5.1.5 on 2025-02-23 08:20

import apps.common.models.fields
import apps.common.utils
import django.core.validators
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=31, unique=True, verbose_name='Menyu nomi')),
                ('short_description', models.CharField(max_length=63, verbose_name='Menu haqida qisqacha')),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.common.utils.generate_upload_path, verbose_name='belgisi(.svg)')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('path', models.CharField(max_length=256, verbose_name='PATH')),
            ],
            options={
                'verbose_name': 'Banner Menyu ',
                'verbose_name_plural': '3. Banner Menyu',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CharityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='sarlavhasi')),
                ('description', models.TextField(max_length=512, verbose_name='batafsil')),
                ('logo', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='logotipi(.svg)')),
                ('app_store_url', models.URLField(verbose_name='app store havolasi')),
                ('google_play_url', models.URLField(verbose_name='google play havolasi')),
            ],
            options={
                'verbose_name': 'Xayriya loyihasi ',
                'verbose_name_plural': '7. Xayriya loyihasi',
            },
        ),
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Instagram rasm',
                'verbose_name_plural': '9. Instagram rasm',
            },
        ),
        migrations.CreateModel(
            name='MusofirDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('amount', models.PositiveBigIntegerField(verbose_name='miqdor')),
                ('date', models.DateTimeField(verbose_name='sanasi')),
                ('note', models.CharField(max_length=255, verbose_name='Eslatma')),
                ('file', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='hujjat')),
            ],
            options={
                'verbose_name': 'Chiqim ',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Yangiliklar uchun obuna emaili ',
                'verbose_name_plural': '8. Yangiliklar uchun obuna emaili',
            },
        ),
        migrations.CreateModel(
            name='PayStatictic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=512, verbose_name='sarlavhasi')),
                ('icon', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='belgisi(.svg)')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='statistika qiymati')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
            ],
            options={
                'verbose_name': 'Xayriya statistikasi ',
                'verbose_name_plural': '2. Xayriya statistikasi',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('quote', models.TextField(verbose_name='iqtibos')),
                ('full_name', models.CharField(max_length=256, verbose_name='F.I.SH')),
                ('job', models.CharField(max_length=256, verbose_name='kasbi')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasmi')),
            ],
            options={
                'verbose_name': 'Iqtibos ',
                'verbose_name_plural': '6. Iqtibos',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=512, verbose_name='sarlavhasi')),
                ('description', models.CharField(max_length=512, verbose_name='tavsifi')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='slider rasmi')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='aktiv')),
                ('title', models.CharField(max_length=256, verbose_name='sarlavhasi')),
                ('logo', models.FileField(upload_to=apps.common.utils.generate_upload_path, verbose_name='logotip(.svg)')),
                ('site_name', models.URLField(verbose_name='sayt nomi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
            ],
            options={
                'verbose_name': 'Foydali manba ',
                'verbose_name_plural': '5. Foydali manbalar',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Menyu nomi')),
                ('order', apps.common.models.fields.OrderField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tartibi')),
                ('path', models.CharField(max_length=256, verbose_name='PATH')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.headermenu', verbose_name='yuqori menyu')),
            ],
            options={
                'verbose_name': 'Header Menyu ',
                'verbose_name_plural': '4. Header Menyu',
                'ordering': ('order',),
            },
        ),
    ]
